<p class="h2_title">{i18n::registration}</p>
<form action="registration/user/" method="post">
    <table cellpadding="0" cellspacing="0" border="0" class="data_table">
        <tr>
            <td>{i18n::login}:</td>
            <td>
                <p>##text->[name=login^validate=login^min=5^max=120]##</p>
                {login_error}
            </td>
        </tr>
        <tr>
            <td>{i18n::email}:</td>
            <td>
                <p>##text->[name=email^validate=email]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::password}:</td>
            <td>
                <p>##password->[name=password^min=5^max=120]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::re_password}:</td>
            <td>
                <p>##password->[name=re_password^min=5^max=120^validate=re_password]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::name}:</td>
            <td>
                <p>##text->[name=name]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::se_name}:</td>
            <td>
                <p>##text->[name=se_name^required=false]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::country}:</td>
            <td>
                <p>##select->[name=country^selected=Other^value={country_val}^text={country_text}]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::city}:</td>
            <td>
                <p>##text->[name=city^required=false]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::your_phone}:</td>
            <td>
                <p>##text->[name=phone^required=false]##</p>
            </td>
        </tr>
        <tr>
            <td>{i18n::enter_code}</td>
            <td>
                <p>
                    <img style="border:1px solid #96A6C5;" src="{captcha}" />
                    <br />
                    ##text->[name=captcha^style=width:131px]##
                    {captcha_error}
                </p>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center;">
                <div>
                    ##submit->[value={i18n::registration}]##
                </div>
            </td>
        </tr>
    </table>
</form>