<p class="h2_title">{i18n::settings}</p>
<form action="settings/save/" method="post">
    <table cellpadding="0" cellspacing="0" border="0" class="data_table">
        <tr>
            <td>
                {i18n::title}:
            </td>
            <td>
                <p>##text->[name=title^value={db::title}]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::keywords}:
            </td>
            <td>
                <p>##textarea->[name=keyword^value={db::keyword}^rows=5^max=1000]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::description}:
            </td>
            <td>
                <p>##textarea->[name=description^value={db::description}^rows=5^max=1000]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::site_open}
            </td>
            <td>
                <p>##radio->[name=enable^checked={db::enable}^value={vals}^text={text}]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::email_backup}:
            </td>
            <td>
                <p>##text->[name=backup_email^value={db::backup_email}^validate=email]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::admin_email}:
            </td>
            <td>
                <p>##text->[name=admin_email^value={db::admin_email}^validate=email]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::email_new_user}
            </td>
            <td>
                <p>##radio->[name=registered_user_mail^checked={db::registered_user_mail}^value={vals}^text={text}]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::inpage}:
            </td>
            <td>
                <p>##text->[name=items_onpage^value={db::items_onpage}^validate=num^max=2^size=4]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::main_page}:
            </td>
            <td>
                <p>##text->[name=main_page^value={db::main_page}]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::auto_backup}:
            </td>
            <td>
                <p>##select->[name=auto_backup^selected={db::auto_backup}^validate=num^max=2^value={hours}^text={text_hours}]##</p>
            </td>
        </tr>
        <tr>
            <td>
                {i18n::copyright}:
            </td>
            <td>
                <p>##text->[name=copyright^value={db::copyright}^size=55]##</p>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center;">
                <div>##submit->[name=submit^value={i18n::save}]##</div>
            </td>
        </tr>
    </table>
</form>